In [1]:
import pickle
import pandas as pd
import matplotlib
import matplotlib.pylab as plt
import scipy as sp
%matplotlib inline
import math
import numpy as np
import seaborn as sms



class Company(object):
    def __init__(self, rec):
        self.rec = rec


#loading cleaned up data from previous competitions and comparison coefficient.
with open('recent_comp.pkl', 'rb') as input:
    rdatac = pickle.load(input)    

recents = rdatac.rec 

In [3]:
#Filtering to keep only those lifters who are somewhat good.
rdata= recents[(recents['NSC']>=-250) & (recents['Weight']>52) &
               (recents['Birth']>=1960) & (recents['Year']>1970)].sort('NSC', ascending=True)

In [5]:
rdata[(rdata['Country']=='USA') & (rdata['Birth']>1990) &(rdata['Year']==2015)]

Lifter    LC Country  CC  Age  Birth  Weight  Year  \
13881  MONTGOMERY Mathew Griffith  6187     USA  15   17   1998   91.90  2015   
14118         SENNETT Ryan Joseph  5791     USA  15   18   1997  133.25  2015   
13710   BEEMER Il Richard Lincoln  6125     USA  15   17   1998   83.70  2015   
13129     COSENTINO Alec Greggory  5933     USA  15   17   1998   61.79  2015   
13687           BURKS Zakary Ryan  6114     USA  15   17   1998   84.30  2015   
13120       DAWSON Gabriel Knight  5929     USA  15   16   1999   61.97  2015   
13854          COOPER Dylan Scott  6176     USA  15   18   1997   89.84  2015   
13667         STEMO Nathan Robert  6108     USA  15   20   1995   82.98  2015   
13472       TROZZI Dominic Robert  5108     USA  15   18   1997   76.35  2015   
13466      TROZZI Dominick Robert  6028     USA  15   18   1997   76.70  2015   
13276           EICHELBERGER Sean  5966     USA  15   20   1995   68.35  2015   
13660    SUMMA Thomas Scott Henry  6103     USA  15   19   1996   83.48  2015   
13275       COHEN William Vincent  4808     USA  15   15   2000   67.15  2015   
13834        COHEN Michael Howard  6167     USA  15   17   1998   91.02  2015   
13446         CUMMINGS Omar Malik  5575     USA  15   17   1998   76.57  2015   
13443       DAMRON Nathan Charles  4525     USA  15   19   1996   76.90  2015   
13261            HUNT Michael Lee  5012     USA  15   20   1995   66.85  2015   
13618          McGOVERN John Luke  4557     USA  15   23   1992   84.54  2015   
13426       MAURUS Harrison James  5506     USA  15   15   2000   74.60  2015   
14096     MOORMAN Spencer Bennett  6243     USA  15   24   1991  108.24  2015   
13969          WILSON Ian Burdick  2975     USA  15   21   1994  104.46  2015   
12879         BARNES Darren Lamar  2392     USA  15   21   1994   55.88  2015   
13191        CUMMINGS JR Clarence  4768     USA  15   15   2000   68.55  2015   

       Snatch  Clean and Jerk  Total         NSC  
13881     121             145    266 -145.629349  
14118     146             175    321 -141.728022  
13710     115             140    255 -141.497944  
13129      92             115    207 -127.214281  
13687     119             154    273 -124.700664  
13120      95             120    215 -119.963983  
13854     130             166    296 -112.072510  
13667     135             151    286 -109.031980  
13472     125             147    272 -108.201151  
13466     125             148    273 -108.051854  
13276     114             136    250 -108.013605  
13660     130             160    290 -106.052672  
13275     113             137    250 -104.126543  
13834     135             174    309 -101.127993  
13446     125             162    287  -93.736866  
13443     130             160    290  -91.534195  
13261     115             147    262  -91.126516  
13618     138             180    318  -80.177053  
13426     135             164    299  -76.815807  
14096     160             200    360  -75.573431  
13969     162             195    357  -73.600629  
12879     105             136    241  -64.030552  
13191     134             168    302  -56.644604

In [4]:
#looking up the stats of possibly the best lifter alive.
recents[recents['LC']==1541]

Lifter    LC Country  CC  Age  Birth  Weight  Year  Snatch  \
2774   ILYIN Ilya  1541     KAZ  28   17   1988   84.65  2005     170   
3282   ILYIN Ilya  1541     KAZ  28   18   1988   93.39  2006     176   
4410   ILYIN Ilya  1541     KAZ  28   20   1988   93.64  2008     180   
6938   ILYIN Ilya  1541     KAZ  28   22   1988   93.68  2010     175   
8287   ILYIN Ilya  1541     KAZ  28   23   1988   93.78  2011     181   
9587   ILYIN Ilya  1541     KAZ  28   24   1988   93.52  2012     185   
12574  ILYIN Ilya  1541     KAZ  28   26   1988  104.35  2014     190   
13923  ILYIN Ilya  1541     KAZ  28   27   1988  104.44  2015     191   

       Clean and Jerk  Total        NSC  
2774              216    386 -12.394513  
3282              225    401 -13.112795  
4410              226    406  -8.522502  
6938              219    394 -20.587873  
8287              226    407  -7.751083  
9587              233    418   3.673912  
12574             242    432   1.548504  
13923             246    437   6.426466

In [4]:
#Since my data has been normalized by the NSC Im not concerned with body weight, so for a given
#lifter, I'll use his country of origin, age and the years he has competed and plot that
#against his coefficient.
X = np.array(rdata[['LC', 'CC', 'Birth', 'Age', 'Year']])
y = np.array(rdata['NSC'])

In [5]:
#Choosing my ML method
from sklearn.neighbors import KNeighborsRegressor

In [6]:
nei = KNeighborsRegressor(n_neighbors=100, weights='distance',
                          algorithm='ball_tree', leaf_size=1000, metric='manhattan')

In [7]:
from sklearn.cross_validation import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

In [9]:
nei.fit(X_train, y_train)

KNeighborsRegressor(algorithm='ball_tree', leaf_size=1000, metric='manhattan',
          metric_params=None, n_neighbors=100, p=2, weights='distance')

In [56]:
#Now that we have our model let's make some predictions for a few lifters to see how it holds.

In [57]:
rdata[rdata['LC']==5968]

Lifter    LC Country  CC  Age  Birth  Weight  Year  Snatch  \
13279  REYES Bruno  5968     PUR  54   20   1995   68.35  2015     110   

       Clean and Jerk  Total         NSC  
13279             137    247 -111.013605

In [10]:
nei.predict([5968,54,1995,21,2016])

array([-110.36782853])

In [11]:
rdata[rdata['LC']==4846]

Lifter    LC Country  CC  Age  Birth  Weight  Year  Snatch  \
11744  LOHIA Igo  4846     PNG  88   15   1999   59.69  2014      75   
11548  LOHIA Igo  4846     PNG  88   15   1999   55.40  2014      70   
13135  LOHIA Igo  4846     PNG  88   16   1999   61.05  2015      87   

       Clean and Jerk  Total         NSC  
11744             100    175 -149.944312  
11548              90    160 -142.157669  
13135             112    199 -132.061167

In [12]:
nei.predict([4846,88,1999,16,2016])

array([-128.08396073])

In [13]:
recents[recents['LC']==3120]

Lifter    LC Country  CC  Age  Birth  Weight  Year  \
5996   CROITORU Florin Ionut  3120     ROU   2   17   1993   55.15  2010   
7387   CROITORU Florin Ionut  3120     ROU   2   18   1993   55.95  2011   
8718   CROITORU Florin Ionut  3120     ROU   2   19   1993   55.90  2012   
8879   CROITORU Florin Ionut  3120     ROU   2   19   1993   61.80  2012   
10202  CROITORU Florin Ionut  3120     ROU   2   20   1993   61.69  2013   
11401  CROITORU Florin Ionut  3120     ROU   2   21   1993   55.68  2014   
11619  CROITORU Florin Ionut  3120     ROU   2   21   1993   61.91  2014   
13020  CROITORU Florin Ionut  3120     ROU   2   22   1993   61.72  2015   

       Snatch  Clean and Jerk  Total        NSC  
5996      110             132    242 -58.622239  
7387      121             149    270 -35.441562  
8718      121             147    268 -37.148185  
8879      132             157    289 -45.256104  
10202     135             155    290 -43.794920  
11401     122             137    259 -44.845230  
11619     126             145    271 -63.714812  
13020     134             153    287 -46.920945

In [14]:
nei.predict([3120,2,1993,23,2016])

array([-72.45455107])

In [15]:
recents[recents['LC']==5810]

Lifter    LC Country  CC  Age  Birth  Weight  Year  \
12830  SITAGATA Malaki Atonio Jr.  5810     ASA  90   15   1999  110.95  2014   
14149  SITAGATA Malaki Atonio Jr.  5810     ASA  90   16   1999  117.46  2015   

       Snatch  Clean and Jerk  Total         NSC  
12830      98             122    220 -218.968538  
14149     107             140    247 -199.612280

In [16]:
nei.predict([5810,90,1999,17,2016])

array([-162.27130699])

In [17]:
nei.predict([5810,91,1999,17,2016])

array([-157.45408356])

In [18]:
recents[recents['LC']==6261]

Lifter    LC Country  CC  Age  Birth  Weight  \
14147  CEDENO HENRIQUEZ Jose Jesus  6261     VEN  48   17   1998   112.9   

       Year  Snatch  Clean and Jerk  Total        NSC  
14147  2015     115             143    258 -183.33069

In [19]:
nei.predict([6261,48,1998,18,2016])

array([-159.12254115])

In [79]:
import dill
with open('nei_model.dill', 'wb') as output:
    dill.dump(nei,output)

In [80]:
with open('nei_model.dill', 'rb') as input:
    nei_model_pred = dill.load(input)

In [81]:
nei_model_pred.predict([6261,48,1998,18,2016])

array([-159.12254115])

In [20]:
class Company1(object):
    def __init__(self, mod):
        self.mod = mod

with open('nei_model.pkl', 'wb') as output:
    recent_c = Company1(nei)
    pickle.dump(recent_c, output, pickle.HIGHEST_PROTOCOL)

In [21]:
with open('nei_model.pkl', 'rb') as input:
    nei_model_predict = pickle.load(input)    

nei_model_predict3 = nei_model_predict.mod

In [ ]:
nei_model_predict3.pre