In [1]:
import pickle
import pandas as pd
import matplotlib
import matplotlib.pylab as plt
import scipy as sp
%matplotlib inline
import math
import numpy as np
import seaborn as sms



class Company(object):
    def __init__(self, rec):
        self.rec = rec


#loading cleaned up data from previous competitions and comparison coefficient.
with open('recent_comp.pkl', 'rb') as input:
    rdatac = pickle.load(input)    

recents = rdatac.rec 

In [2]:
#Filtering to keep only those lifters who are somewhat good.
rdata= recents[(recents['NSC']>=-250) & (recents['Weight']>52) &
               (recents['Birth']>=1960) & (recents['Year']>1970)].sort('NSC', ascending=True)

In [3]:
rdata.head()

Lifter    LC Country   CC  Age  Birth  Weight  \
12825             ALMUTAIRI Hamad  5805     KUW  136   18   1996  153.48   
11132        JOLLY Ryan Alexander  5260     NZL   61   17   1996   85.25   
4407              TIAKIA P. Simon  2224     NIU  132   16   1992   82.30   
5951   AL ANSARI Issa Ibrahim A A  3110     QAT   68   23   1986  123.30   
13921               ALMURI Hamdan  6215     QAT   68   17   1998   93.50   

       Year  Snatch  Clean and Jerk  Total         NSC  
12825  2014     110             120    230 -249.735676  
11132  2013      70              80    150 -249.571022  
4407   2008      60              85    145 -248.623984  
5951   2009      95             110    205 -247.932184  
13921  2015      77              90    167 -247.293308

In [4]:
#looking up the stats of possibly the best lifter alive.
recents[recents['LC']==1541]

Lifter    LC Country  CC  Age  Birth  Weight  Year  Snatch  \
2774   ILYIN Ilya  1541     KAZ  28   17   1988   84.65  2005     170   
3282   ILYIN Ilya  1541     KAZ  28   18   1988   93.39  2006     176   
4410   ILYIN Ilya  1541     KAZ  28   20   1988   93.64  2008     180   
6938   ILYIN Ilya  1541     KAZ  28   22   1988   93.68  2010     175   
8287   ILYIN Ilya  1541     KAZ  28   23   1988   93.78  2011     181   
9587   ILYIN Ilya  1541     KAZ  28   24   1988   93.52  2012     185   
12574  ILYIN Ilya  1541     KAZ  28   26   1988  104.35  2014     190   
13923  ILYIN Ilya  1541     KAZ  28   27   1988  104.44  2015     191   

       Clean and Jerk  Total        NSC  
2774              216    386 -12.394513  
3282              225    401 -13.112795  
4410              226    406  -8.522502  
6938              219    394 -20.587873  
8287              226    407  -7.751083  
9587              233    418   3.673912  
12574             242    432   1.548504  
13923             246    437   6.426466

In [50]:
#Since my data has been normalized by the NSC Im not concerned with body weight, so for a given
#lifter, I'll use his country of origin, age and the years he has competed and plot that
#against his coefficient.
X = np.array(rdata[['LC', 'CC', 'Birth', 'Age', 'Year']])
y = np.array(rdata['NSC'])

In [51]:
#Choosing my ML method
from sklearn.neighbors import KNeighborsRegressor

In [52]:
nei = KNeighborsRegressor(n_neighbors=100, weights='distance',
                          algorithm='ball_tree', leaf_size=1000, metric='manhattan')

In [53]:
from sklearn.cross_validation import train_test_split

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

In [55]:
nei.fit(X_train, y_train)

KNeighborsRegressor(algorithm='ball_tree', leaf_size=1000, metric='manhattan',
          metric_params=None, n_neighbors=100, p=2, weights='distance')

In [56]:
#Now that we have our model let's make some predictions for a few lifters to see how it holds.

In [57]:
rdata[rdata['LC']==5968]

Lifter    LC Country  CC  Age  Birth  Weight  Year  Snatch  \
13279  REYES Bruno  5968     PUR  54   20   1995   68.35  2015     110   

       Clean and Jerk  Total         NSC  
13279             137    247 -111.013605

In [58]:
nei.predict([5968,54,1995,21,2016])

array([-110.36782853])

In [59]:
rdata[rdata['LC']==4846]

Lifter    LC Country  CC  Age  Birth  Weight  Year  Snatch  \
11744  LOHIA Igo  4846     PNG  88   15   1999   59.69  2014      75   
11548  LOHIA Igo  4846     PNG  88   15   1999   55.40  2014      70   
13135  LOHIA Igo  4846     PNG  88   16   1999   61.05  2015      87   

       Clean and Jerk  Total         NSC  
11744             100    175 -149.944312  
11548              90    160 -142.157669  
13135             112    199 -132.061167

In [60]:
nei.predict([4846,88,1999,16,2016])

array([-128.08396073])

In [61]:
recents[recents['LC']==3120]

Lifter    LC Country  CC  Age  Birth  Weight  Year  \
5996   CROITORU Florin Ionut  3120     ROU   2   17   1993   55.15  2010   
7387   CROITORU Florin Ionut  3120     ROU   2   18   1993   55.95  2011   
8718   CROITORU Florin Ionut  3120     ROU   2   19   1993   55.90  2012   
8879   CROITORU Florin Ionut  3120     ROU   2   19   1993   61.80  2012   
10202  CROITORU Florin Ionut  3120     ROU   2   20   1993   61.69  2013   
11401  CROITORU Florin Ionut  3120     ROU   2   21   1993   55.68  2014   
11619  CROITORU Florin Ionut  3120     ROU   2   21   1993   61.91  2014   
13020  CROITORU Florin Ionut  3120     ROU   2   22   1993   61.72  2015   

       Snatch  Clean and Jerk  Total        NSC  
5996      110             132    242 -58.622239  
7387      121             149    270 -35.441562  
8718      121             147    268 -37.148185  
8879      132             157    289 -45.256104  
10202     135             155    290 -43.794920  
11401     122             137    259 -44.845230  
11619     126             145    271 -63.714812  
13020     134             153    287 -46.920945

In [68]:
nei.predict([3120,2,1993,23,2016])

array([-72.45455107])

In [63]:
recents[recents['LC']==5810]

Lifter    LC Country  CC  Age  Birth  Weight  Year  \
12830  SITAGATA Malaki Atonio Jr.  5810     ASA  90   15   1999  110.95  2014   
14149  SITAGATA Malaki Atonio Jr.  5810     ASA  90   16   1999  117.46  2015   

       Snatch  Clean and Jerk  Total         NSC  
12830      98             122    220 -218.968538  
14149     107             140    247 -199.612280

In [64]:
nei.predict([5810,90,1999,17,2016])

array([-162.27130699])

In [77]:
nei.predict([5810,91,1999,17,2016])

array([-157.45408356])

In [65]:
recents[recents['LC']==6261]

Lifter    LC Country  CC  Age  Birth  Weight  \
14147  CEDENO HENRIQUEZ Jose Jesus  6261     VEN  48   17   1998   112.9   

       Year  Snatch  Clean and Jerk  Total        NSC  
14147  2015     115             143    258 -183.33069

In [66]:
nei.predict([6261,48,1998,18,2016])

array([-159.12254115])

In [79]:
import dill
with open('nei_model.dill', 'wb') as output:
    dill.dump(nei,output)

In [80]:
with open('nei_model.dill', 'rb') as input:
    nei_model_pred = dill.load(input)

In [81]:
nei_model_pred.predict([6261,48,1998,18,2016])

array([-159.12254115])